### ISSUE TITLE
Collaborative programming does not support multiple parameters, making it inconvenient to use. Like the go language, which can pass multiple parameters

### ISSUE THREAD

**Issue by aliveyun** [zelang-dev/c-coroutine#2]
Collaborative programming does not support multiple parameters, making it inconvenient to use. Like the go language, which can pass multiple parameters
coroutine void worker(int count, const char *text) {
    int i;
    for(i = 0; i != count; ++i) {
        printf("%s\n", text);
        msleep(now() + 10);
    }
}

int main() {
    go(worker(4, "a"));
    go(worker(2, "b"));
    go(worker(3, "c"));
    msleep(now () + 100);
    return 0;
}

**Comment by TheTechsTech** [comment]
What? Not sure what you are getting at. Where is your example and output that's not the same? Maybe you should look in the example folder here.

> "Collaborative programming..."

Is that another idiom for **users** and not **developers.**? Copying only gets you so far.

Maybe you referencing https://github.com/golang/go/wiki/CommonMistakes or maybe something in http://golang50shad.es/ which is still not the issue you showing.

**Comment by TheTechsTech** [comment]
**GoLang** like other modern languages is a already a high level language that is actually holding your hand and restricting. 

This library provides a means you get same high level behavior without any hand holding, you free do whatever. 

Maybe you should stay with something that's doing the thinking for you, which means your not actually needed, can be replaced with **ChatGPT**. 

Maybe you should learn the internals of those languages of how they work, before saying anything about "not support multiple parameters".
